#pragma once
#include <Windows.h>
#include "../../src/data/Data.h"

namespace Setting {

    namespace Player {
        extern int BoxType;
        extern int BoxTypeColor;
        extern int SnapLinesType;
        extern int SkeletonType;
        extern int RadarType;
        extern bool Details;
        extern bool Box;
        extern bool SnapLines;
        extern bool Skeleton;
        extern int SkeletonStyle;
        extern bool Name;
        extern bool Distance;
        extern bool Weapon;
        extern bool WeaponAsIcon;  /* show weapon as icon when true */
        extern bool WeaponColorDefault;
        extern bool AimStatus;
        extern bool ZonePrediction;
        extern bool Radar;
        extern bool VisibleCheck;
        extern bool EachBone;
        extern float Box_ThickNess;
        extern float SnapLines_ThickNess;
        extern float Skeleton_ThickNess;
        extern float Distance_ThickNess;
        extern float Name_ThickNess;
        extern float Weapon_ThickNess;
        extern float AimStatus_ThickNess;
        extern float ZonePrediction_ThickNess;
        extern float Radar_Distance;
        extern float ESP_OffsetX;
        extern float ESP_OffsetY;
        extern float Box_Color[4];
        extern float SnapLines_Color[4];
        extern float Skeleton_Color[4];
        extern float Distance_Color[4];
        extern float Name_Color[4];
        extern float NameBorder_Color[4];
        extern float Weapon_Color[4];
        extern float AimStatus_Color[4];
        extern float ZonePrediction_Color[4];
        extern float VisibleCheck_Color[4];
        extern float VisibleCheckPart2_Color[4];
        extern float VisibleCheckPart3_Color[4];
        extern float VisibleCheckPart4_Color[4];
        namespace Miscellanouse {
            extern int HealthID;
            extern bool PlayerUID;
            extern bool Health;
            extern bool Nation;
            extern bool TeamIDCol;
            extern float PlayerUID_ThickNess;
            extern float Health_ThickNess;
            extern float PlayerUID_Color[4];
            extern float Health_Color[4];
        } // namespace Miscellanouse
    }     // namespace Player
    namespace PickupItems {
        namespace Visual {
            extern int SkipItemsKey;
            extern bool DetailsItems;
            extern bool DistanceItems;
            extern bool SkipItems;
            extern bool IsShowItems;
            extern bool ShowItemInDeathBox;
        } // namespace Visual
        namespace Rifles {
            extern bool M16A4;
            extern bool SCARL;
            extern bool M416;
            extern bool FAMAS;
            extern bool QBZ;
            extern bool G63C;
            extern bool AUG;
            extern bool AKM;
            extern bool M762;
            extern bool HoneyBadger;
            extern bool GROZA;
            extern bool MK14;
            extern float M16A4_ThickNess;
            extern float SCARL_ThickNess;
            extern float M416_ThickNess;
            extern float FAMAS_ThickNess;
            extern float QBZ_ThickNess;
            extern float G63C_ThickNess;
            extern float AUG_ThickNess;
            extern float AKM_ThickNess;
            extern float M762_ThickNess;
            extern float HoneyBadger_ThickNess;
            extern float GROZA_ThickNess;
            extern float MK14_ThickNess;
            extern float M16A4_Color[4];
            extern float SCARL_Color[4];
            extern float M416_Color[4];
            extern float FAMAS_Color[4];
            extern float QBZ_Color[4];
            extern float G63C_Color[4];
            extern float AUG_Color[4];
            extern float AKM_Color[4];
            extern float M762_Color[4];
            extern float HoneyBadger_Color[4];
            extern float GROZA_Color[4];
            extern float MK14_Color[4];
        }; // namespace Rifles
        namespace SMG {
            extern bool THOMPSON;
            extern bool UMP45;
            extern bool P90;
            extern bool UZI;
            extern bool BIZON;
            extern bool MP5K;
            extern bool VECTOR;
            extern float THOMPSON_ThickNess;
            extern float UMP45_ThickNess;
            extern float P90_ThickNess;
            extern float UZI_ThickNess;
            extern float BIZON_ThickNess;
            extern float MP5K_ThickNess;
            extern float VECTOR_ThickNess;
            extern float THOMPSON_Color[4];
            extern float UMP45_Color[4];
            extern float P90_Color[4];
            extern float UZI_Color[4];
            extern float BIZON_Color[4];
            extern float MP5K_Color[4];
            extern float VECTOR_Color[4];
        }; // namespace SMG
        namespace Sniper {
            extern bool WIN94;
            extern bool VSS;
            extern bool MINI14;
            extern bool QBU;
            extern bool MK12;
            extern bool MK47;
            extern bool SLR;
            extern bool SKS;
            extern bool KAR98;
            extern bool MOSIN;
            extern bool BOW;
            extern bool AWM;
            extern bool AMR;
            extern float WIN94_ThickNess;
            extern float VSS_ThickNess;
            extern float MINI14_ThickNess;
            extern float QBU_ThickNess;
            extern float MK12_ThickNess;
            extern float MK47_ThickNess;
            extern float SLR_ThickNess;
            extern float SKS_ThickNess;
            extern float KAR98_ThickNess;
            extern float MOSIN_ThickNess;
            extern float BOW_ThickNess;
            extern float AWM_ThickNess;
            extern float AMR_ThickNess;
            extern float WIN94_Color[4];
            extern float VSS_Color[4];
            extern float MINI14_Color[4];
            extern float QBU_Color[4];
            extern float MK12_Color[4];
            extern float MK47_Color[4];
            extern float SLR_Color[4];
            extern float SKS_Color[4];
            extern float KAR98_Color[4];
            extern float MOSIN_Color[4];
            extern float BOW_Color[4];
            extern float AWM_Color[4];
            extern float AMR_Color[4];
        }; // namespace Sniper
        namespace AutoMachine {
            extern bool M249;
            extern bool MG3;
            extern bool DP28;
            extern float M249_ThickNess;
            extern float MG3_ThickNess;
            extern float DP28_ThickNess;
            extern float M249_Color[4];
            extern float MG3_Color[4];
            extern float DP28_Color[4];
        }; // namespace AutoMachine
        namespace ShotGun {
            extern bool S686;
            extern bool S1897;
            extern bool M1014;
            extern bool Neostead2000;
            extern bool S12K;
            extern bool DBS;
            extern float S686_ThickNess;
            extern float S1897_ThickNess;
            extern float M1014_ThickNess;
            extern float Neostead2000_ThickNess;
            extern float S12K_ThickNess;
            extern float DBS_ThickNess;
            extern float S686_Color[4];
            extern float S1897_Color[4];
            extern float M1014_Color[4];
            extern float Neostead2000_Color[4];
            extern float S12K_Color[4];
            extern float DBS_Color[4];
        }; // namespace ShotGun
        namespace Pistols {
            extern bool P1911;
            extern bool R45;
            extern bool DesertEagle;
            extern bool P92;
            extern bool P18C;
            extern bool Vz61;
            extern bool R1895;
            extern bool Flaregun;
            extern float P1911_ThickNess;
            extern float R45_ThickNess;
            extern float DesertEagle_ThickNess;
            extern float P92_ThickNess;
            extern float P18C_ThickNess;
            extern float Vz61_ThickNess;
            extern float R1895_ThickNess;
            extern float Flaregun_ThickNess;
            extern float P1911_Color[4];
            extern float R45_Color[4];
            extern float DesertEagle_Color[4];
            extern float P92_Color[4];
            extern float P18C_Color[4];
            extern float Vz61_Color[4];
            extern float R1895_Color[4];
            extern float Flaregun_Color[4];
        } // namespace Pistols
        namespace NeccessaryHealth {
            extern bool Adrenaline;
            extern bool EnergyDrink;
            extern bool Painkiller;
            extern bool FirstaidKit;
            extern bool Medkit;
            extern float Adrenaline_ThickNess;
            extern float EnergyDrink_ThickNess;
            extern float Painkiller_ThickNess;
            extern float FirstaidKit_ThickNess;
            extern float Medkit_ThickNess;
            extern float Adrenaline_Color[4];
            extern float EnergyDrink_Color[4];
            extern float Painkiller_Color[4];
            extern float FirstaidKit_Color[4];
            extern float Medkit_Color[4];
        }; // namespace NeccessaryHealth
        namespace Melee {
            extern bool Pan;
            extern float Pan_ThickNess;
            extern float Pan_Color[4];
        }; // namespace Melee
        namespace Bag {
            extern bool BagLv1;
            extern bool BagLv2;
            extern bool BagLv3;
            extern float BagLv1_ThickNess;
            extern float BagLv2_ThickNess;
            extern float BagLv3_ThickNess;
            extern float BagLv1_Color[4];
            extern float BagLv2_Color[4];
            extern float BagLv3_Color[4];
        }; // namespace Bag
        namespace Armor {
            extern bool ArmorLv1;
            extern bool ArmorLv2;
            extern bool ArmorLv3;
            extern float ArmorLv1_ThickNess;
            extern float ArmorLv2_ThickNess;
            extern float ArmorLv3_ThickNess;
            extern float ArmorLv1_Color[4];
            extern float ArmorLv2_Color[4];
            extern float ArmorLv3_Color[4];
        }; // namespace Armor
        namespace Helmet {
            extern bool HelmetLv1;
            extern bool HelmetLv2;
            extern bool HelmetLv3;
            extern float HelmetLv1_ThickNess;
            extern float HelmetLv2_ThickNess;
            extern float HelmetLv3_ThickNess;
            extern float HelmetLv1_Color[4];
            extern float HelmetLv2_Color[4];
            extern float HelmetLv3_Color[4];
        }; // namespace Helmet
        namespace Accessory {
            extern bool AREx;
            extern bool ARExQk;
            extern bool LargeCompensator;
            extern bool LargeSuppressor;
            extern bool SniperCompensator;
            extern bool SniperSuppressor;
            extern bool ThumbGrip;
            extern bool Angled;
            extern bool LightGrip;
            extern bool HalfGrip;
            extern bool Vertical;
            extern bool Reddot;
            extern bool Holo;
            extern bool Scope2X;
            extern bool Scope3X;
            extern bool Scope4X;
            extern bool Scope6X;
            extern bool Scope8X;
            extern bool M416Stock;
            extern float AREx_ThickNess;
            extern float ARExQk_ThickNess;
            extern float LargeCompensator_ThickNess;
            extern float LargeSuppressor_ThickNess;
            extern float SniperCompensator_ThickNess;
            extern float SniperSuppressor_ThickNess;
            extern float ThumbGrip_ThickNess;
            extern float Angled_ThickNess;
            extern float LightGrip_ThickNess;
            extern float HalfGrip_ThickNess;
            extern float Vertical_ThickNess;
            extern float Reddot_ThickNess;
            extern float Holo_ThickNess;
            extern float Scope2X_ThickNess;
            extern float Scope3X_ThickNess;
            extern float Scope4X_ThickNess;
            extern float Scope6X_ThickNess;
            extern float Scope8X_ThickNess;
            extern float M416Stock_ThickNess;
            extern float AREx_Color[4];
            extern float ARExQk_Color[4];
            extern float LargeCompensator_Color[4];
            extern float LargeSuppressor_Color[4];
            extern float SniperCompensator_Color[4];
            extern float SniperSuppressor_Color[4];
            extern float ThumbGrip_Color[4];
            extern float Angled_Color[4];
            extern float LightGrip_Color[4];
            extern float HalfGrip_Color[4];
            extern float Vertical_Color[4];
            extern float Reddot_Color[4];
            extern float Holo_Color[4];
            extern float Scope2X_Color[4];
            extern float Scope3X_Color[4];
            extern float Scope4X_Color[4];
            extern float Scope6X_Color[4];
            extern float Scope8X_Color[4];
            extern float M416Stock_Color[4];
        }; // namespace Accessory
        namespace Ammo {
            extern bool Ammo762;
            extern bool Ammo45ACP;
            extern bool Ammo556;
            extern bool Ammo9;
            extern bool Ammo300Magnum;
            extern bool Ammo12Guage;
            extern bool AmmoFlareGun;
            extern float Ammo762_ThickNess;
            extern float Ammo45ACP_ThickNess;
            extern float Ammo556_ThickNess;
            extern float Ammo9_ThickNess;
            extern float Ammo300Magnum_ThickNess;
            extern float Ammo12Guage_ThickNess;
            extern float AmmoFlareGun_ThickNess;
            extern float Ammo762_Color[4];
            extern float Ammo45ACP_Color[4];
            extern float Ammo556_Color[4];
            extern float Ammo9_Color[4];
            extern float Ammo300Magnum_Color[4];
            extern float Ammo12Guage_Color[4];
            extern float AmmoFlareGun_Color[4];
        }; // namespace Ammo
        namespace Others {
            extern bool AirDrop;
            extern bool DeathBox;
            extern bool Grenade;
            extern bool Smoke;
            extern bool Molotof;
            extern bool Apple;
            extern bool Gascan;
            extern bool TokenShop;
            extern bool SecurityCard;
            extern float AirDrop_ThickNess;
            extern float DeathBox_ThickNess;
            extern float Grenade_ThickNess;
            extern float Smoke_ThickNess;
            extern float Molotof_ThickNess;
            extern float Apple_ThickNess;
            extern float Gascan_ThickNess;
            extern float TokenShop_ThickNess;
            extern float SecurityCard_ThickNess;
            extern float AirDrop_Color[4];
            extern float DeathBox_Color[4];
            extern float Grenade_Color[4];
            extern float Smoke_Color[4];
            extern float Molotof_Color[4];
            extern float Apple_Color[4];
            extern float Gascan_Color[4];
            extern float TokenShop_Color[4];
            extern float SecurityCard_Color[4];
        }; // namespace Others
    }      // namespace PickupItems
    namespace Vehicle {
        extern bool Vehicle;
        extern bool Vehicle_Details;
        extern bool Vehicle_HP;
        extern bool Vehicle_Fuel;
        extern bool Vehicle_Distance;
        extern bool VehicleChange;
        extern bool VehicleSkip;
        extern bool IsShowVehicle;
        extern int VehicleSkipkey;
        extern float Vehicle_ThickNess;
        extern float Vehicle_Color[4];
        extern float VehicleChange_Color[4];
        extern bool Vehicle_Box;
        extern bool Vehicle_DirectionLine;
        extern float VehicleLineDirectionSize;
        extern bool Vehicle_Warning;
        extern bool Vehicle_WheelDamage;
        extern int Vehicle_VehType;       /* 0=Icons+Text, 1=Bar, 2=Text only (Unity-style) */
        extern int Vehicle_MaxDistance;   /* max render distance in meters */
    } // namespace Vehicle
    namespace Alerts {
        extern bool OpenAllAlert;
        extern bool GrenadeAlert;
        extern bool MolotufAlert;
        extern bool SmokeAlert;
        extern bool RedzoneAlert;
        extern bool GrenadeAlert_Trajectory;
        extern float GrenadeAlert_ThickNess;
        extern float MolotufAlert_ThickNess;
        extern float SmokeAlert_ThickNess;
        extern float RedzoneAlert_ThickNess;
        extern float GrenadeAlert_Color[4];
        extern float MolotufAlert_Color[4];
        extern float SmokeAlert_Color[4];
        extern float RedzoneAlert_Color[4];
        extern float GrenadeAlert_Trajectory_Color[4];
    } // namespace Alerts
    namespace Memory {
        extern bool FastRun;
        extern bool HighRiskFastCar;
        extern bool IpadViewRunning;
        extern bool UseInventorySkinMap;
        extern float SHBV;
        extern bool MagicBullet;
        extern bool AutoMagic;
        extern bool Extended;
        extern bool bShowDame;
        extern bool bWallShot;
        extern bool bTeleport;
        extern int  bTeleportKey;
        extern bool bFastCar;
        extern bool bFlyCar;
        extern int FlyCarKey;
        extern float FlyCarValue;
        extern bool bTeleportToCar;
        extern bool bNoRecoil;
        extern bool bInstantHit;
        extern float InstantHitValue;
        extern bool bRoomMode;
        extern bool bInfiniteAmmo;
        extern bool bAnimation;
        extern int TypeMouse;
        extern int TypeMethod;
        extern int SpeedShoot;
        extern float BaseFire;
        extern float CalcFireSpeed;
        extern float CalculateBaseFire;
        extern int GodUpValue;
        extern bool bAntiMemory;

        extern bool bModAttachment;
        extern bool bModEffect;
        extern bool bGodView;
        extern bool bSilentGodView;
        extern bool xEffect;
        extern bool xEffectHead_ColorRandom;
        extern bool xEffectBody_ColorRandom;
        extern bool CrosshairColor;
        extern bool JumpProne;
        extern bool LessRecoil;
        extern bool CameraSpin;
        extern bool AutoReport;
        extern bool bUnlockFPS;
        extern bool bUnlockGraphics;
        extern bool bBigWeapon;
        extern bool bScaleDance;
        extern bool BigPlayer;
        extern bool bBigVehicle;
        extern int JumpType;
        extern float BigVehicleValue;
        extern float BigPlayerValue;
        // SPEED -- 
        extern bool FastRunV1;
        extern bool FastRunV2;
        extern int FastRunV2Mode;
        extern int FastRunV2Key;
        extern float FastRunV2Value;
        extern bool FastRunV3;
        extern int FastRunV3Mode;
        extern int FastRunV3Key;
        extern float FastRunV3Value;
        extern bool FastRunV4;
        extern int FastRunV4Mode;
        extern int FastRunV4Key;
        extern float FastRunV4Value;
        extern bool FastRunV5;
        extern int FastRunV5Key;
        extern int FastRunV5Mode;
        extern float FastRunV5Move;
        extern float FastRunV5World;
        extern bool PositionControl;
        extern int PositionControlKey;
        extern int PositionControlMode;
        extern float PositionControlValue;
        extern bool StopLocal;
        extern int PositionTick;
        // SPEED --
        extern bool bHighJump;
        extern int bHighJumpKey;
        extern int bHighJumpValue;
        extern bool bFly;
        extern int bFlyKey;
        extern float bFlyValue;
        extern bool bNoGravity;
        extern bool FastParachute;
        extern int FastParachuteKeybUP;
        extern int FastParachuteKeybDOWN;
        extern bool SpinBot;
        extern float MagicValue;
        extern int FastCarForwardKey;
        extern int FastCarBackwardKey;
        extern int AntiMemoryValue;
        extern int GodviewTopKey;
        extern int GodviewBotKey;
        extern int GodviewFrontKey;
        extern int GodviewLeftKey;
        extern int GodviewRightKey;
        extern float SGV_Value;

        extern int xEffectScale;
        extern int JumpProneKey;
        extern int JumpKey;
        extern int ProneKey;
        extern int LessRecoilType;
        extern int CameraSpinYaw;
        extern int CameraSpinPitch;
        extern int CameraSpinKey;
        extern int CountReport;
        extern int BigWeaponValue;
        extern int SpinBotSpeed;
        extern int SpinBotKey;
        extern float xEffectHead_Color[4];
        extern float xEffectBody_Color[4];

    } // namespace Memory
    namespace SpecialFeatures {
        extern bool FixFlash;
        extern bool DangerMode;
        extern bool HideName;
        extern bool MacroSpeed;
        extern bool GameInformation;
        extern bool ArNearest;
        extern bool BlackSky;
        extern bool AutoTCP;
        extern bool AutoUDP;
        extern bool bAllTCP;
        extern bool bAllUDP;
        extern bool MessageKill;
        extern bool DeadBox;
        extern bool AutoMagicCar;
        extern bool ParachuteAssist;
        extern bool SlowAnimation;
        extern bool BirdMode;
        extern bool FogOfWar;
        extern bool ESPD;
        extern int V3Selector;
        extern bool DevMode;
        extern bool AutoFire;
        extern bool WWCDPost;

        extern int V3Fov;
        extern bool V3SkipKnock;
        extern bool V3SkipBot;
        extern bool UCCWFov;
        extern float HeadPosZi;
        extern bool AimbotInternal;

        extern float GameFPS;
        extern int FieldOfView;
        extern int CacheVer;
        extern float ThirdPersonFOV;
        extern float ScopeFOV;
        extern bool IpadView;
        extern int IpadViewValue;
        extern bool FPS120;
        extern bool UltraHD;
        /* Players/Bots red bar (PLAYERS (0) || BOTS (0)) */
        extern float RedBarLength;   /* half-width, 50–200, default 115 */
        extern float RedBarHeight;   /* bar height 18–50, default 27 */
        extern float RedBarTextOffset; /* text left/right offset in px, -100–100, default -26 */
    } // namespace SpecialFeatures
    namespace MemoryHacks {
        extern bool bSpeedHack;
        extern float fSpeedMultiplier;
        extern bool bNoRecoil;
        extern bool bNoSpread;
        extern bool bInstantHit;
        extern bool bFastSwitch;
        extern bool bInfiniteAmmo;
        extern bool bVehicleBoost;
        extern float fVehicleBoostMultiplier;
        extern bool bHighJump;
        extern float fHighJumpMultiplier;
        extern bool bNoFallDamage;
        extern bool bFOVUnlock;
        extern float fFOVMin;
        extern float fFOVMax;
        extern bool bNoGrass;
        extern bool bRadar;
        extern bool bESPThroughWalls;
        extern bool bVehicleFly;
        extern bool bTeleport;
        extern int iTeleportKey;
        extern bool bRapidFire;
        extern float fRapidFireScale;
        extern bool bNoWeaponSway;
        extern bool bExtendedRange;
        extern float fRangeMultiplier;
        extern bool bDamageScale;
        extern float fDamageMultiplier;
        extern bool bFastParachuteExtra;
        extern bool bInstantMed;
        extern bool bVehicleNoDamage;
        extern bool bNoFlash;
    }
    namespace ESPExtras {
        extern bool bSnaplines;
        extern bool bDistanceColor;
        extern float fDistanceNear;
        extern float fDistanceFar;
        extern bool bHealthBarStyle;
        extern float fSkeletonThickness;
        extern bool bFOVFilterESP;
        extern bool bThreatHighlight;
        extern float ThreatHighlight_Color[4];
        extern bool bRecentlyShotHighlight;
        extern float RecentlyShotHighlight_Color[4];
        extern float fRecentlyShotDurationSec;
    }
    namespace AimbotExtras {
        extern bool bHumanizedAim;
        extern float fAimSmooth;
        extern int iAimBone;
        extern bool bStickyAim;
        extern float fStickyThreshold;
        extern bool bAutoSwitchTarget;
        extern bool bPrediction;
    }
    namespace QoL {
        extern bool bKeyHints;
        extern bool bFPSOverlay;
        extern bool bMatchStats;
        extern bool bSafeZoneTimer;
        extern bool bCustomCrosshair;
        extern float fCrosshairSize;
        extern float fCrosshairColor[4];
        extern int iTheme;
        extern bool bNotificationHistory;
        extern bool bPingOverlay;
        extern bool bSessionTimer;
        extern bool bCompass;
        extern bool bWaypoint;
        extern float fWaypointX;
        extern float fWaypointY;
        extern float fWaypointZ;
        extern bool bEnemyLastSeen;
        extern bool bShowSpectatorList;
        extern bool bESPWhenSpectating;
    }
    namespace MenuExtras {
        extern bool bSearchMenu;
        extern char sSearchBuf[128];
        extern bool bSaveMenuPosition;
        extern int iConfigPreset;
        extern bool bKeybindList;
    }
    namespace BulletTrack {
        extern bool AutoFix;
        extern bool CameraCache;
        extern bool OpenAim;
        extern bool BypassFovLitmit;
        extern float ZPosition;
    }// namespace BulletTrack
    extern bool ShowMenu;
    extern bool ShowSide;
    extern bool InfoOverlay;

    extern int InfoOverlayVer;
    extern bool AimAlternative;

    extern bool AimAssist;
    extern bool BypassAssistDistance;
    extern float AssistSpeed;
    extern float AssistFOV;

    extern bool Predict;
    extern bool AimLimitDistance;
    extern bool Fov;
    extern bool Macro;
    extern bool MacroWithAim;
    extern bool ShootKnock;
    extern bool SkipAI;
    extern bool AimLine;
    extern bool AimLineColTeamID;
    extern bool AimLineChange;
    extern bool LockEnemyPressAim;
    // Language system
    enum Language {
        ENGLISH = 0,
        VIETNAMESE = 1,
        TURKISH = 2,
        RUSSIAN = 3,
        CHINESE = 4
    };
    extern Language CurrentLanguage;
    extern bool LanguageVNM; // Keep for backward compatibility
    extern bool HideHack;
    extern bool BorderString;
    extern bool AutoTap;
    extern bool BulletCheckVisible;
    extern bool LibmoduleEsp;
    extern float PredictAim;
    extern float AimLimitDistanceValue;
    extern float AimLimitDistanceValueScope;
    extern float Fov_Color[4];
    extern float AimLine_Color[4];
    extern float AimLineChangeCol_Color[4];
    extern int TypeAim;
    extern int TargetAim;
    extern int KeyAim;
    extern int FovAim;
    extern int FovAimScope;
    extern int SmoothAim;
    extern int MacroAim;
    extern int KeyShootKnock;
    extern int AutoTapDelay;
    extern int UpdateTick;
    extern int MenuTick;
    extern int UpdateModuleTick;
    extern float AimLine_ThickNess;
    extern bool Watermark;
    extern int BackgroundTransparency;
    extern int MenuTransparency;
    extern float MenuFontSize;
    extern float ImportantFontSize;
    extern bool AntiScreenCapture;
    extern bool DiscordRPC;
    extern bool bOverlayHidden;

    namespace Animation {
        extern bool bRainbowBorder;
        extern bool bRGBTabs;
        extern bool bPulseText;
        extern bool bMovingParticles;
        extern int iParticleMode; // 0: Plexus, 1: Snow, 2: Floating
        extern float fAnimationSpeed;
    }
} // namespace Setting
namespace Cheat
{
    extern float Test1;

    extern float Test2;
    extern float Test3;
    extern bool Unload;
    extern bool IsOpenGL;
    extern bool ModuleLoaded;
    extern bool IsNeedModule;
    extern bool IsLogin;
    extern bool ModuleMSGLoaded;
    extern bool ModuleCarLoaded;
    extern bool ModuleDeadBoxLoaded;
    extern bool ModuleSkeletonLoaded;
    extern int UploadPicture;
    extern bool UploadPic;

    extern LPVOID ModuleCheat;
    extern HINSTANCE Module;
}
namespace EspSetting
{
    extern bool ResetEsp;
}