#pragma once
#include <Windows.h>
#include <iostream>
#define SERVER_NAME "onyxcheats.alwaysdata.net"
namespace Offset
{
    const DWORD GameState = 0x2f8; // GameStateBase* GameState -> Class: World.Object
    const DWORD bNoAliveHumanPlayer = 0x7dc;
    const DWORD PersistentLevel = 0x20; // Level* PersistentLevel -> Class: World.Object
    const DWORD NetDriver = 0x24; // NetDriver* NetDriver -> Class: World.Object
    const DWORD CustomTimeDilation = 0xb4; // float CustomTimeDilation -> Class: Actor.Object
    const DWORD ReplicatedMovement = 0xd8; // RepMovement ReplicatedMovement -> Class: Actor.Object
    const DWORD bAutoDestroyWhenFinished = 0x190; // bool bAutoDestroyWhenFinished -> Class: Actor.Object
    const DWORD GameModeBase = 0x2f4; // GameModeBase* AuthorityGameMode -> Class: World.Object
    const DWORD RootComponent = 0x1b0; // SceneComponent* RootComponent -> Class: Actor.Object
    const DWORD ActorsClassGC = 0x3f8; // Player* Player -> Class: PlayerController.Controller.Actor.Object
    const DWORD AcknowledgedPawn = 0x390; // Pawn* AcknowledgedPawn -> Class: PlayerController.Controller.Actor.Object
    const DWORD MyHUD = 0x40c; // HUD* MyHUD -> Class: PlayerController.Controller.Actor.Object
    const DWORD PlayerCameraManager = 0x410; // PlayerCameraManager* PlayerCameraManager -> Class: PlayerController.Controller.Actor.Object
    const DWORD WorldSetting = 0x308; // WorldSettings* WorldSettings -> Class: Level.Object
    const DWORD ServerConnection = 0x64; // NetConnection* ServerConnection -> Class: NetDriver.Object
    const DWORD PlayerController = 0x20; // PlayerController* PlayerController -> Class: Player.Object
    const DWORD Controller = 0x3cc; // Controller* Controller -> Class: Pawn.Actor.Object
    const DWORD ElapsedTime = 0x3f0; // int ElapsedTime -> Class: GameState.GameStateBase.Info.Actor.Object
    const DWORD NoneAIGameTime = 0x854;
    const DWORD CirclePain = 0x574; // float CirclePain -> Class: STExtraGameStateBase.UAEGameState.LuaGameState.GameState.GameStateBase.Info.Actor.Object
    const DWORD PlayerNum = 0x654; // int PlayerNum -> Class: STExtraGameStateBase.UAEGameState.LuaGameState.GameState.GameStateBase.Info.Actor.Object
    const DWORD RealPlayerNum = 0x654;
    const DWORD CurCircleWave = 0x93C; // int CurCircleWave -> Class: STExtraGameStateBase.UAEGameState.LuaGameState.GameState.GameStateBase.Info.Actor.Object
    const DWORD AlivePlayerNum = 0x934; // int AlivePlayerNum -> Class: STExtraGameStateBase.UAEGameState.LuaGameState.GameState.GameStateBase.Info.Actor.Object
    const DWORD AliveTeamNum = 0x938; // int AliveTeamNum -> Class: STExtraGameStateBase.UAEGameState.LuaGameState.GameState.GameStateBase.Info.Actor.Object
    const DWORD PlayerNumPerTeam = 0xb44; // int PlayerNumPerTeam -> Class: STExtraGameStateBase.UAEGameState.LuaGameState.GameState.GameStateBase.Info.Actor.Object
    const DWORD GameModeID = 0xd38; // FString GameModeID -> Class: STExtraGameStateBase.UAEGameState.LuaGameState.GameState.GameStateBase.Info.Actor.Object
    const DWORD GameModeState = 0x8d8;
    const DWORD GameID = 0xd30; // uint64 GameID -> Class: STExtraGameStateBase.UAEGameState.LuaGameState.GameState.GameStateBase.Info.Actor.Object
    const DWORD IsFPPGameMode = 0x7E0; // bool IsFPPGameMode -> Class: STExtraGameStateBase.UAEGameState.LuaGameState.GameState.GameStateBase.Info.Actor.Object
    const DWORD IsCanSwitchFPP = 0x7e9; // bool IsCanSwitchFPP -> Class: STExtraGameStateBase.UAEGameState.LuaGameState.GameState.GameStateBase.Info.Actor.Object
    const DWORD GameReplayType = 0x7d8; // int GameReplayType -> Class: UAEPlayerController.LuaPlayerController.PlayerController.Controller.Actor.Object
    const DWORD ServerZoneId = 0x768;
    const DWORD PlayerKeyController = 0x714; // uint32 PlayerKey -> Class: UAEPlayerController.LuaPlayerController.PlayerController.Controller.Actor.Object
    const DWORD Position = 0x1B0; // STExtraBaseCharacter* TargetCharacter -> Class: UAERotatingMovementComponent.RotatingMovementComponent.MovementComponent.ActorComponent.Object
    const DWORD Health = 0xae8; // float Health -> Class: STExtraCharacter.UAECharacter.Character.Pawn.Actor.Object
    const DWORD HealthMax = 0xaec; // float HealthMax -> Class: STExtraCharacter.UAECharacter.Character.Pawn.Actor.Object
    const DWORD CurrentVehicle = 0xb24; // STExtraVehicleBase* CurrentVehicle -> Class: STExtraCharacter.UAECharacter.Character.Pawn.Actor.Object
    const DWORD CurrentStates = 0xc20; // uint64 CurrentStates -> Class: STExtraCharacter.UAECharacter.Character.Pawn.Actor.Object
    const DWORD bIsGunADS = 0xcf4; // bool bIsGunADS ->
    const DWORD bIsAirOpen = 0x570;
    const DWORD Kills = 0x528;
    const DWORD bDead = 0xb00; // bool bDead -> Class: STExtraCharacter.UAECharacter.Character.Pawn.Actor.Object
    const DWORD IsDead = 0xad8;
    const DWORD bAIIgnore = 0xb01; // bool bAIIgnore -> Class: STExtraCharacter.UAECharacter.Character.Pawn.Actor.Object
    const DWORD PartHitComponent = 0xcdc; // PartHitComponent* PartHitComponent -> Class: STExtraCharacter.UAECharacter.Character.Pawn.Actor.Object
    const DWORD ConfigCollisionDistSqAngles = 0x178; // OpenCollisionLODAngle[] ConfigCollisionDistSqAngles -> Class: PartHitComponent.ActorComponent.Object
    const DWORD SpeedScale = 0xd14; // float SpeedScale -> Class: STExtraCharacter.UAECharacter.Character.Pawn.Actor.Object
    const DWORD PlayerState = 0x3c4; // PlayerState* PlayerState -> Class: Pawn.Actor.Object
    const DWORD Status = 0x3c0;
    const DWORD Name = 0x720; // FString PlayerName -> Class: UAECharacter.Character.Pawn.Actor.Object
    const DWORD Nation = 0x72c; // FString Nation -> Class: UAECharacter.Character.Pawn.Actor.Object
    const DWORD PlayerUID = 0x73c; // FString PlayerUID -> Class: UAECharacter.Character.Pawn.Actor.Object
    const DWORD TeamId = 0x748; // int TeamID -> Class: UAECharacter.Character.Pawn.Actor.Object
    const DWORD bTeamLeader = 0x758; // bool bTeamLeader -> Class: UAECharacter.Character.Pawn.Actor.Object
    const DWORD bIsAI = 0x7d4; // bool bIsAI -> Class: UAECharacter.Character.Pawn.Actor.Object
    const DWORD IsBot = 0x7e1;
    const DWORD bEnsure = 0x7ed; // bool bEnsure -> Class: UAECharacter.Character.Pawn.Actor.Object
    const DWORD bRepEnsure = 0x7ef; // bool bRepEnsure -> Class: UAECharacter.Character.Pawn.Actor.Object
    const DWORD bMEnsure = 0x7ee; // bool bMEnsure -> Class: UAECharacter.Character.Pawn.Actor.Object
    const DWORD PlayerKeyAActor = 0x738; // uint32 PlayerKey -> Class: UAECharacter.Character.Pawn.Actor.Object
    const DWORD BreathMax = 0x164; // float BreathMax -> Class: STCharacterNearDeathComp.ActorComponent.Object
    const DWORD Breath = 0x18c; // float Breath -> Class: STCharacterNearDeathComp.ActorComponent.Object
    const DWORD Mesh = 0x3f0; // SkeletalMeshComponent* Mesh -> Class: Character.Pawn.Actor.Object
    const DWORD Chams_bDrawHighlight         = 0x368; // byte offset, bit 2=bDrawHighlight, bit 8=bOverrideHighlightColor
    const DWORD Chams_HighlightColor          = 0x36c; // LinearColor (R,G,B,A as 4 floats)
    const DWORD Chams_bRenderCustomDepth      = 0x3b8; // byte offset, bit 128=bRenderCustomDepth
    const DWORD Chams_CustomDepthStencilValue = 0x3c0; // int
    const DWORD CharacterMovement = 0x3f4; // CharacterMovementComponent* CharacterMovement -> Class: Character.Pawn.Actor.Object
    const DWORD bIsCrouched = 0x4b4; // bool bIsCrouched -> Class: Character.Pawn.Actor.Object
    const DWORD SkeletalMesh = 0x7d4; // SkeletalMesh* SkeletalMesh -> Class: SkinnedMeshComponent.MeshComponent.PrimitiveComponent.SceneComponent.ActorComponent.Object
    const DWORD Velocity = 0x128; // Vector Velocity -> Class: MovementComponent.ActorComponent.Object
    const DWORD ControlRotation = 0x3c8; // Rotator ControlRotation -> Class: Controller.Actor.Object
    const DWORD LastUpdateVelocity = 0x2b0; // Vector LastUpdateVelocity -> Class: CharacterMovementComponent.PawnMovementComponent.NavMovementComponent.MovementComponent.ActorComponent.Object
    const DWORD MaxWalkSpeed = 0x1d4; // float MaxWalkSpeed -> Class: CharacterMovementComponent.PawnMovementComponent.NavMovementComponent.MovementComponent.ActorComponent.Object
    const DWORD bMaintainHorizontalGroundVelocity = 0x3c3; // bool bMaintainHorizontalGroundVelocity -> Class: CharacterMovementComponent.PawnMovementComponent.NavMovementComponent.MovementComponent.ActorComponent.Object
    const DWORD EnergySpeedScale = 0x21e4; // float EnergySpeedScale -> Class: CharacterMovementComponent.PawnMovementComponent.NavMovementComponent.MovementComponent.ActorComponent.Object
    const DWORD MaxWalkSpeedCrouched = 0x1d8; // float MaxWalkSpeedCrouched -> Class: CharacterMovementComponent.PawnMovementComponent.NavMovementComponent.MovementComponent.ActorComponent.Object
    const DWORD MaxSwimSpeed = 0x1dc; // float MaxSwimSpeed -> Class: CharacterMovementComponent.PawnMovementComponent.NavMovementComponent.MovementComponent.ActorComponent.Object
    const DWORD MaxFlySpeed = 0x1e0; // float MaxFlySpeed -> Class: CharacterMovementComponent.PawnMovementComponent.NavMovementComponent.MovementComponent.ActorComponent.Object
    const DWORD JumpZVelocity = 0x19c; // float JumpZVelocity -> Class: CharacterMovementComponent.PawnMovementComponent.NavMovementComponent.MovementComponent.ActorComponent.Object
    const DWORD MaxStepHeight = 0x198; // float MaxStepHeight -> Class: CharacterMovementComponent.PawnMovementComponent.NavMovementComponent.MovementComponent.ActorComponent.Object
    const DWORD MaxCustomMovementSpeed = 0x1e4; // float MaxCustomMovementSpeed -> Class: CharacterMovementComponent.PawnMovementComponent.NavMovementComponent.MovementComponent.ActorComponent.Object
    const DWORD MaxAcceleration = 0x1e8; // float MaxAcceleration -> Class: CharacterMovementComponent.PawnMovementComponent.NavMovementComponent.MovementComponent.ActorComponent.Object
    const DWORD bCheatFlying = 0x3c8; // bool bCheatFlying -> Class: CharacterMovementComponent.PawnMovementComponent.NavMovementComponent.MovementComponent.ActorComponent.Object
    const DWORD bApplyGravityWhileJumping = 0x190; // bool bApplyGravityWhileJumping -> Class: CharacterMovementComponent.PawnMovementComponent.NavMovementComponent.MovementComponent.ActorComponent.Object
    const DWORD GravityScale = 0x194; // float GravityScale -> Class: CharacterMovementComponent.PawnMovementComponent.NavMovementComponent.MovementComponent.ActorComponent.Object
    const DWORD RelativeLocation = 0x178; // Vector RelativeLocation -> Class: SceneComponent.ActorComponent.Object
    const DWORD RelativeRotation = 0x184; // Rotator RelativeRotation -> Class: SceneComponent.ActorComponent.Object
    const DWORD RelativeScale3D = 0x190; // Vector RelativeScale3D -> Class: SceneComponent.ActorComponent.Object
    const DWORD ComponentVelocity = 0x250; // Vector ComponentVelocity -> Class: SceneComponent.ActorComponent.Object
    const DWORD LastSubmitTime = 0x394; // float LastSubmitTime -> Class: PrimitiveComponent.SceneComponent.ActorComponent.Object
    const DWORD LastRenderTime = 0x398; // float LastRenderTime -> Class: PrimitiveComponent.SceneComponent.ActorComponent.Object
    const DWORD LastRenderTimeOnScreen = 0x39c; // float LastRenderTimeOnScreen -> Class: PrimitiveComponent.SceneComponent.ActorComponent.Object
    const DWORD MinLOD = 0x7f4; // int MinLOD -> Class: StaticMeshComponent.MeshComponent.PrimitiveComponent.SceneComponent.ActorComponent.Object
    const DWORD Skeletal = 0x7e8; // SkeletalMesh* SkeletalMesh -> Class: SkinnedMeshComponent.MeshComponent.PrimitiveComponent.SceneComponent.ActorComponent.Object
    const DWORD Asset = 0xf0; // PhysicsAsset* PhysicsAsset -> Class: SkeletalMesh.Object
    const DWORD ArraySkeletal = 0x28; // SkeletalBodySetup*[] SkeletalBodySetups -> Class: PhysicsAsset.Object
    const DWORD X_BONE = 0x88; // float X -> Class: KBoxElem.KShapeElem
    const DWORD Y_BONE = 0x8c; // float Y -> Class: KBoxElem.KShapeElem
    const DWORD Z_BONE = 0x90; // float Z -> Class: KBoxElem.KShapeElem
    const DWORD VehicleMovement = 0x182c; // STExtraVehicleMovementComponent4W* VehicleMovement -> Class: STExtraWheeledVehicle.STExtraVehicleBase.Pawn.Actor.Object
    const DWORD ExtraBoostFactor = 0x199c; // float ExtraBoostFactor -> Class: STExtraWheeledVehicle.STExtraVehicleBase.Pawn.Actor.Object
    const DWORD CameraShakeInnerRadius = 0x218; // float CameraShakeInnerRadius -> Class: ShootWeaponEffectComponent.WeaponEffectComponent.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD CameraShakeOuterRadius = 0x21C; // float CameraShakeOuterRadius -> Class: ShootWeaponEffectComponent.WeaponEffectComponent.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD CameraShakFalloff = 0x220; // float CameraShakFalloff -> Class: ShootWeaponEffectComponent.WeaponEffectComponent.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD bDrawDebug = 0x3e0; // bool bDrawDebug -> Class: ShootWeaponEffectComponent.WeaponEffectComponent.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD LaunchGravityScale = 0x488; // float LaunchGravityScale -> Class: STExtraShootWeaponBulletBase.LuaActor.Actor.Object
    const DWORD BulletTrackDistanceFix = 0x774; // float BulletTrackDistanceFix ->
    const DWORD BulletTrackDistance = 0x774;
    const DWORD BulletFireSpeed = 0x484; // float BulletFireSpeed -> Class: ShootWeaponEntity.WeaponEntity.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD ShootInterval = 0x4b4; // float ShootInterval -> Class: ShootWeaponEntity.WeaponEntity.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD ExtraShootInterval = 0x4bc; // float ExtraShootInterval -> Class: ShootWeaponEntity.WeaponEntity.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD DeviationInfo = 0x9e0; // SDeviation DeviationInfo -> Class: ShootWeaponEntity.WeaponEntity.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD bHasSingleFireMode = 0x500; // bool bHasSingleFireMode -> Class: ShootWeaponEntity.WeaponEntity.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD bHasAutoFireMode = 0x501; // bool bHasAutoFireMode -> Class: ShootWeaponEntity.WeaponEntity.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD bHasBurstFireMode = 0x502; // bool bHasBurstFireMode -> Class: ShootWeaponEntity.WeaponEntity.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD BurstShootInterval = 0x530; // float BurstShootInterval -> Class: ShootWeaponEntity.WeaponEntity.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD BulletNumSingleShot = 0x538; // int BulletNumSingleShot -> Class: ShootWeaponEntity.WeaponEntity.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD BaseImpactDamage = 0x5b4; // float BaseImpactDamage -> Class: ShootWeaponEntity.WeaponEntity.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD VehicleDamageScale = 0x5bc; // float VehicleDamageScale -> Class: ShootWeaponEntity.WeaponEntity.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD BulletMomentum = 0x5c0; // float BulletMomentum -> Class: ShootWeaponEntity.WeaponEntity.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD AccessoriesVRecoilFactor = 0x9c4; // float AccessoriesVRecoilFactor -> Class: ShootWeaponEntity.WeaponEntity.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD AccessoriesHRecoilFactor = 0x9cc; // float AccessoriesHRecoilFactor -> Class: ShootWeaponEntity.WeaponEntity.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD AccessoriesRecoveryFactor = 0x9c8; // float AccessoriesRecoveryFactor -> Class: ShootWeaponEntity.WeaponEntity.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD BulletRange = 0x5d0; // float BulletRange -> Class: ShootWeaponEntity.WeaponEntity.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD RangeModifier = 0x5e0; // float RangeModifier -> Class: ShootWeaponEntity.WeaponEntity.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD TraceDistance = 0x62c; // float TraceDistance -> Class: ShootWeaponEntity.WeaponEntity.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD MaxDamageRate = 0x680; // float MaxDamageRate -> Class: ShootWeaponEntity.WeaponEntity.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD DamageImpulse = 0x778; // float DamageImpulse -> Class: ShootWeaponEntity.WeaponEntity.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD ReloadRate = 0x7bc; // float ReloadRate -> Class: ShootWeaponEntity.WeaponEntity.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD DropDuration = 0x854; // float DropDuration -> Class: ShootWeaponEntity.WeaponEntity.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD ShotGunCenterPerc = 0xa20; // float ShotGunCenterPerc -> Class: ShootWeaponEntity.WeaponEntity.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD ShotGunVerticalSpread = 0xa24; // float ShotGunVerticalSpread -> Class: ShootWeaponEntity.WeaponEntity.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD ShotGunHorizontalSpread = 0xa28; // float ShotGunHorizontalSpread -> Class: ShootWeaponEntity.WeaponEntity.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD GameDeviationFactor = 0xa18; // float GameDeviationFactor -> Class: ShootWeaponEntity.WeaponEntity.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD GameDeviationAccuracy = 0xa1c; // float GameDeviationAccuracy -> Class: ShootWeaponEntity.WeaponEntity.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD AccessoriesDeviationFactor = 0x9dc; // float AccessoriesDeviationFactor -> Class: ShootWeaponEntity.WeaponEntity.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD CrossHairInitialSize = 0xa14; // float CrossHairInitialSize -> Class: ShootWeaponEntity.WeaponEntity.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD CrossHairBurstSpeed = 0xa30; // float CrossHairBurstSpeed -> Class: ShootWeaponEntity.WeaponEntity.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD CrossHairBurstIncreaseSpeed = 0xa34; // float CrossHairBurstIncreaseSpeed -> Class: ShootWeaponEntity.WeaponEntity.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD VehicleWeaponDeviationAngle = 0xa38; // float VehicleWeaponDeviationAngle -> Class: ShootWeaponEntity.WeaponEntity.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD bDrawCrosshairWhenScope = 0xa3c; // bool bDrawCrosshairWhenScope -> Class: ShootWeaponEntity.WeaponEntity.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD RecoilKickADS = 0xad8; // float RecoilKickADS -> Class: ShootWeaponEntity.WeaponEntity.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD RecoilInfo = 0x960; // SRecoilInfo RecoilInfo -> Class: ShootWeaponEntity.WeaponEntity.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD AnimationKick = 0xadc; // float AnimationKick -> Class: ShootWeaponEntity.WeaponEntity.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD ExtraHitPerformScale = 0xae0; // float ExtraHitPerformScale -> Class: ShootWeaponEntity.WeaponEntity.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD bHasInfiniteClips = 0x620; // bool bHasInfiniteClips -> Class: ShootWeaponEntity.WeaponEntity.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD bClipHasInfiniteBullets = 0x621; // bool bClipHasInfiniteBullets -> Class: ShootWeaponEntity.WeaponEntity.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD AutoAimingConfig = 0x860; // AutoAimingConfig AutoAimingConfig -> Class: ShootWeaponEntity.WeaponEntity.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD bIsEngineStarted = 0x92c; // bool bIsEngineStarted -> Class: STExtraVehicleBase.Pawn.Actor.Object
    const DWORD VehicleCommon = 0x95c; // VehicleCommonComponent* VehicleCommon -> Class: STExtraVehicleBase.Pawn.Actor.Object
    const DWORD lastForwardSpeed = 0x9f0; // float lastForwardSpeed -> Class: STExtraVehicleBase.Pawn.Actor.Object
    const DWORD vHPMax = 0x278; // float HPMax -> Class: VehicleCommonComponent.VehicleComponent.LuaActorComponent.ActorComponent.Object
    const DWORD HPMax = 0x26c;
    const DWORD vHP = 0x27c; // float HP ->
    const DWORD HP = 0x270; // Class: VehicleCommonComponent.VehicleComponent.LuaActorComponent.ActorComponent.Object
    const DWORD WheelsCurrentHP = 0x2d4; // float[] WheelsCurrentHP -> Class: VehicleCommonComponent.VehicleComponent.LuaActorComponent.ActorComponent.Object
    const DWORD vFuelMax = 0x328; // float FuelMax -> Class: VehicleCommonComponent.VehicleComponent.LuaActorComponent.ActorComponent.Object
    const DWORD FuelMax = 0x314;
    const DWORD vFuel = 0x32c; // float Fuel ->
    const DWORD Fuel = 0x318; // Class: VehicleCommonComponent.VehicleComponent.LuaActorComponent.ActorComponent.Object
    const DWORD PickUpDataList = 0x788; // PickUpItemData[] PickUpDataList -> Class: PickUpListWrapperActor.PickUpWrapperActor.UAENetActor.LuaActor.Actor.Object
    const DWORD boxItemsCount = 0x788; // enum BoxType -> Class: PickUpListWrapperActor.PickUpWrapperActor.UAENetActor.LuaActor.Actor.Object
    const DWORD ItemDefineID = 0x4a0; // ItemDefineID DefineID -> Class: PickUpWrapperActor.UAENetActor.LuaActor.Actor.Object
    const DWORD Count = 0x4b8; // int Count -> Class: PickUpWrapperActor.UAENetActor.LuaActor.Actor.Object
    const DWORD TypeSpecificID = 0x4; // int TypeSpecificID -> Class: ItemDefineID
    const DWORD STPlayerController = 0x3b28; // STExtraPlayerController* STPlayerController -> Class: STExtraPlayerCharacter.STExtraBaseCharacter.STExtraCharacter.UAECharacter.Character.Pawn.Actor.Object
    const DWORD STPlayerController1 = 0x3b28;
    const DWORD CameraCache = 0x420; // CameraCacheEntry CameraCache -> Class: PlayerCameraManager.Actor.Object
    const DWORD MinUndilatedFrameTime = 0x5ec; // float MinUndilatedFrameTime -> Class: WorldSettings.Info.Actor.Object
    const DWORD IsGameModeFpp = 0x7c8; // int IsGameModeFpp -> Class: UAEGameMode.LuaGameMode.GameMode.GameModeBase.Info.Actor.Object
    const DWORD CharacterOverrideAttrs = 0xed0; // CharacterOverrideAttrData[] CharacterOverrideAttrs -> Class: UAEGameMode.LuaGameMode.GameMode.GameModeBase.Info.Actor.Object
    const DWORD pExtraGameState = 0x244; // STExtraGameStateBase* pExtraGameState -> Class: MapUIMarkManager.LuaActorComponent.ActorComponent.Object
    const DWORD CurrentFallSpeed = 0x1a8; // float CurrentFallSpeed -> Class: CharacterParachuteComponent.LuaInstancedActorComponent.ActorComponent.Object
    const DWORD FreeFall_AcceFall = 0x1d0; // float FreeFall_AcceFall -> Class: CharacterParachuteComponent.LuaInstancedActorComponent.ActorComponent.Object
    const DWORD FreeFall_MaxFreeFallSpeed = 0x1d4; // float FreeFall_MaxFreeFallSpeed -> Class: CharacterParachuteComponent.LuaInstancedActorComponent.ActorComponent.Object
    const DWORD FreeFall_AcceForward = 0x1dc; // float FreeFall_AcceForward -> Class: CharacterParachuteComponent.LuaInstancedActorComponent.ActorComponent.Object
    const DWORD FreeFall_MaxForwardExtraFallSpeed = 0x1e8; // float FreeFall_MaxForwardExtraFallSpeed -> Class: CharacterParachuteComponent.LuaInstancedActorComponent.ActorComponent.Object
    const DWORD Opened_AcceFall = 0x21c; // float Opened_AcceFall -> Class: CharacterParachuteComponent.LuaInstancedActorComponent.ActorComponent.Object
    const DWORD Opened_MaxFreeFallSpeed = 0x220; // float Opened_MaxFreeFallSpeed -> Class: CharacterParachuteComponent.LuaInstancedActorComponent.ActorComponent.Object
    const DWORD Opened_AcceForward = 0x224; // float Opened_AcceForward -> Class: CharacterParachuteComponent.LuaInstancedActorComponent.ActorComponent.Object
    const DWORD Opened_MaxForwardSpeed = 0x228; // float Opened_MaxForwardSpeed -> Class: CharacterParachuteComponent.LuaInstancedActorComponent.ActorComponent.Object
    const DWORD Opened_MaxForwardExtraFallSpeed = 0x230; // float Opened_MaxForwardExtraFallSpeed -> Class: CharacterParachuteComponent.LuaInstancedActorComponent.ActorComponent.Object
    const DWORD AllowMaxDiatanceSqAtServer = 0x2a0; // float AllowMaxDiatanceSqAtServer -> Class: CharacterParachuteComponent.LuaInstancedActorComponent.ActorComponent.Object
    const DWORD MaxZAllowDistance = 0x2ac; // float MaxZAllowDistance -> Class: CharacterParachuteComponent.LuaInstancedActorComponent.ActorComponent.Object
    const DWORD FieldOfView = 0x31c; // float FieldOfView -> Class: CameraComponent.SceneComponent.ActorComponent.Object
    const DWORD bIsFPPOnVehicle = 0x11b0; // bool bIsFPPOnVehicle -> Class: STExtraBaseCharacter.STExtraCharacter.UAECharacter.Character.Pawn.Actor.Object
    const DWORD bIsWeaponFiring = 0x1218; // bool bIsWeaponFiring -> Class: STExtraBaseCharacter.STExtraCharacter.UAECharacter.Character.Pawn.Actor.Object
    const DWORD PoseState = 0x1228; // byte PoseState -> Class: STExtraBaseCharacter.STExtraCharacter.UAECharacter.Character.Pawn.Actor.Object
    const DWORD WeaponManagerComponent = 0x1d80; // CharacterWeaponManagerComponent* WeaponManagerComponent -> Class: STExtraBaseCharacter.STExtraCharacter.UAECharacter.Character.Pawn.Actor.Object
    const DWORD SwitchWeaponSpeedScale = 0x2200; // float SwitchWeaponSpeedScale -> Class: STExtraBaseCharacter.STExtraCharacter.UAECharacter.Character.Pawn.Actor.Object
    const DWORD NearDeatchComponent = 0x1560; // STCharacterNearDeathComp* NearDeatchComponent -> Class: STExtraBaseCharacter.STExtraCharacter.UAECharacter.Character.Pawn.Actor.Object
    const DWORD NearDeathBreath = 0x1570; // float NearDeathBreath -> Class: STExtraBaseCharacter.STExtraCharacter.UAECharacter.Character.Pawn.Actor.Object
    const DWORD ScopeFov = 0x1650; // float ScopeFov -> Class: STExtraBaseCharacter.STExtraCharacter.UAECharacter.Character.Pawn.Actor.Object
    const DWORD CameraComponent = 0x1684; // CameraComponent* ThirdPersonCameraComponent -> Class: STExtraBaseCharacter.STExtraCharacter.UAECharacter.Character.Pawn.Actor.Object
    const DWORD CameraComponentVehicle = 0x1414; // CameraComponent* vehicle camera (iPad view)
    const DWORD ScopeCameraComp = 0x1694; // CameraComponent* ScopeCameraComp -> Class: STExtraBaseCharacter.STExtraCharacter.UAECharacter.Character.Pawn.Actor.Object
    const DWORD STCharacterMovement = 0x1758; // STCharacterMovementComponent* STCharacterMovement -> Class: STExtraBaseCharacter.STExtraCharacter.UAECharacter.Character.Pawn.Actor.Object
    const DWORD IsFakeOnVehicle = 0x1789; // bool IsFakeOnVehicle -> Class: STExtraBaseCharacter.STExtraCharacter.UAECharacter.Character.Pawn.Actor.Object
    const DWORD IsNetFPP = 0x1970; // bool IsNetFPP -> Class: STExtraBaseCharacter.STExtraCharacter.UAECharacter.Character.Pawn.Actor.Object
    const DWORD IsFPP = 0x1988; // bool IsFPP -> Class: STExtraBaseCharacter.STExtraCharacter.UAECharacter.Character.Pawn.Actor.Object
    const DWORD CurrentReloadWeapon = 0x25d4; // STExtraWeapon* CurrentReloadWeapon -> Class: STExtraBaseCharacter.STExtraCharacter.UAECharacter.Character.Pawn.Actor.Object
    const DWORD ParachuteComponent = 0x120c; // CharacterParachuteComponent* ParachuteComponent -> Class: STExtraBaseCharacter.STExtraCharacter.UAECharacter.Character.Pawn.Actor.Object
    const DWORD CharacterParachuteComponent = 0x120c;
    const DWORD SpringArmComp = 0x167c; // CustomSpringArmComponent* SpringArmComp -> Class: STExtraBaseCharacter.STExtraCharacter.UAECharacter.Character.Pawn.Actor.Object
    const DWORD ScopeSpringArmComp = 0x1680; // SpringArmComponent* ScopeSpringArmComp -> Class: STExtraBaseCharacter.STExtraCharacter.UAECharacter.Character.Pawn.Actor.Object
    const DWORD MeshContainer = 0x1508; // SceneComponent* MeshContainer -> Class: STExtraBaseCharacter.STExtraCharacter.UAECharacter.Character.Pawn.Actor.Object
    const DWORD StandHalfHeight = 0x22c0; // float StandHalfHeight -> Class: STExtraBaseCharacter.STExtraCharacter.UAECharacter.Character.Pawn.Actor.Object
    const DWORD CrouchHalfHeight = 0x22c4; // float CrouchHalfHeight -> Class: STExtraBaseCharacter.STExtraCharacter.UAECharacter.Character.Pawn.Actor.Object
    const DWORD ProneHalfHeight = 0x22c8; // float ProneHalfHeight -> Class: STExtraBaseCharacter.STExtraCharacter.UAECharacter.Character.Pawn.Actor.Object
    const DWORD AvatarComponent2 = 0x23e0; // CharacterAvatarComponent2* AvatarComponent2 -> Class: STExtraBaseCharacter.STExtraCharacter.UAECharacter.Character.Pawn.Actor.Object
    const DWORD IsInvincible = 0x11a8; // bool IsInvincible -> Class: STExtraBaseCharacter.STExtraCharacter.UAECharacter.Character.Pawn.Actor.Object
    const DWORD STExtraBaseCharacter = 0x1f78; // STExtraBaseCharacter* STExtraBaseCharacter -> Class: STExtraPlayerController.UAEPlayerController.LuaPlayerController.PlayerController.Controller.Actor.Object
    const DWORD CrossHairColors = 0x12d4; // LinearColor CrossHairColor -> Class: STExtraPlayerController.UAEPlayerController.LuaPlayerController.PlayerController.Controller.Actor.Object
    const DWORD CurrentWeaponReplicated = 0x4bc; // STExtraWeapon* CurrentWeaponReplicated -> Class: WeaponManagerComponent.ActorComponent.Object
    const DWORD ShootWeaponComponent = 0xc50; // STExtraShootWeaponComponent* ShootWeaponComponent -> Class: STExtraShootWeapon.STExtraWeapon.LuaActor.Actor.Object
    const DWORD CurBulletNumInClip = 0xcf8; // int CurBulletNumInClip -> Class: STExtraShootWeapon.STExtraWeapon.LuaActor.Actor.Object
    const DWORD CurMaxBulletNumInOneClip = 0xd08; // int CurMaxBulletNumInOneClip -> Class: STExtraShootWeapon.STExtraWeapon.LuaActor.Actor.Object
    const DWORD ShootWeaponEntityComp = 0xf8c; // ShootWeaponEntity* ShootWeaponEntityComp -> Class: STExtraShootWeapon.STExtraWeapon.LuaActor.Actor.Object
    const DWORD ShootWeaponEntity = 0x1110;
    const DWORD ShootWeaponEffectComp = 0xf90; // ShootWeaponEffectComponent* ShootWeaponEffectComp -> Class: STExtraShootWeapon.STExtraWeapon.LuaActor.Actor.Object
    const DWORD ShootMode = 0xd95;
    const DWORD OwnerShootWeapon = 0x23c; // STExtraShootWeapon* OwnerShootWeapon -> Class: STExtraShootWeaponComponent.WeaponLogicBaseComponent.ActorComponent.Object
    const DWORD HitPerform = 0x4b0; // HitPerformData HitPerform -> Class: SurviveHUD.HUD.Actor.Object
    const DWORD HitBodyDrawColor = 0x30; // LinearColor HitBodyDrawColor -> Class: HitPerformData
    const DWORD HitHeadDrawColor = 0x40; // LinearColor HitHeadDrawColor -> Class: HitPerformData
    const DWORD HitToDeathDrawColor = 0x60; // LinearColor HitToDeathDrawColor -> Class: HitPerformData
    const DWORD AlphaDecreaseSpeed = 0x28; // float AlphaDecreaseSpeed -> Class: HitPerformData
    const DWORD HeadExtraScale = 0x14; // float HeadExtraScale -> Class: HitPerformData
    const DWORD AddSpreadScale = 0x18; // float AddSpreadScale -> Class: HitPerformData
    const DWORD NetAvatarData = 0x300; // NetAvatarSyncData NetAvatarData -> Class: SlotAvatarComponent.AvatarComponentBase.LuaActorComponent.ActorComponent.Object
    const DWORD SynData = 0x5f8; // MeshSynData[] synData -> Class: STExtraWeapon.LuaActor.Actor.Object
    const DWORD CachedLocalBounds = 0x8e4; // BoxSphereBounds CachedLocalBounds -> Class: SkinnedMeshComponent.MeshComponent.PrimitiveComponent.SceneComponent.ActorComponent.Object
    const DWORD bMoveable = 0x1efc; // bool bMoveable -> Class: STExtraPlayerController.UAEPlayerController.LuaPlayerController.PlayerController.Controller.Actor.Object
    const DWORD MinTimeBetweenTimeStampResets = 0x69c; // float MinTimeBetweenTimeStampResets -> Class: CharacterMovementComponent.PawnMovementComponent.NavMovementComponent.MovementComponent.ActorComponent.Object
    const DWORD MatineeTimeDilation = 0x5dc; // float MatineeTimeDilation -> Class: WorldSettings.Info.Actor.Object
    const DWORD Wheels = 0x1e4 + 0x10; // VehicleWheel*[] Wheels -> Class: WheeledVehicleMovementComponent.PawnMovementComponent.NavMovementComponent.MovementComponent.ActorComponent.Object
    // - > Library - > libUE4.so
    // -> Base Offset
    const DWORD UE4Pointer = 0xE0C3860;
    const DWORD GName = 0xA371594;
    const DWORD GWorld = 0xA761894;
    const DWORD ViewMatrix = 0xA740214;  // ViewWorld
    const DWORD GUObject = 0xe7680f0;
    // -> iPad View
    const DWORD IpadView = 0x6434468;
    const DWORD ScopeGL = 0x3FCC464;
    // -> Extra Offset
    const DWORD CurrentWeapon = 0x20d0 - 0x4;
    // -> Don't Change - >
    const DWORD BodyAddv = 0x1a0;
    const DWORD EntityList = 0x70;
    const DWORD EntityCount = EntityList + 0x4;
    /* Lobby: STExtraLobbyCharacter - play emote. Try these; update from dump if needed: */
    const DWORD LobbyCharacter_PlayEmote = 0x11E0;   /* primary */
    const DWORD LobbyCharacter_PlayEmote_Alt1 = 0x11D8;
    const DWORD LobbyCharacter_PlayEmote_Alt2 = 0x11DC;
    const DWORD LobbyCharacter_PlayEmote_Alt3 = 0x11E4;
}
